---
title: Promise学习02
tags: [ES6]
---
# promise学习02
## promise.resolve
静态方法`Promise.resolve(value)`，可以认为是`new Promise()`方法的快捷方式。`Promise.resolve(value)`的返回值也是一个promise。
```
Promise.resolve(42).then(function(value){
    console.log(value);
});
```
`Promise.resolve`作为`new Promise()`的快捷方式，在进行promise对象的初始化或者编写测试代码的时候非常方便。   
## promise.reject
`Promise.reject(error)`是和`Promise.resolve(value)`类似的静态方法，是`new Promise()`方法的快捷方式。
调用代码实例：
```
Promise.reject(new Error("BOOM!")).catch(function(error){
    console.error(error);
});
```
## Promise只能做异步操作？
在使用`Promise.resolve(value)`等方法的时候，如果`promise`对象立刻进入resolve状态的话，`.then`里面指定的方法是同步调用吗？但是，实际上`.then`方法调用是异步进行的。
```
var promise = new Promise(function (resolve){
    console.log("inner promise"); // 1
    resolve(42);
});
promise.then(function(value){
    console.log(value); // 3
});
console.log("outer promise"); // 2
```
执行顺序为:
```
inner promise // 1
outer promise // 2
42            // 3
```
即使在调用`promise.then`注册回调函数的时候promise对象已经是确定状态，promise也会以异步的方式调用该回调函数，这是promise设计上的规定方针。  


## Promise#then
promise可以写成方法链的形式
```
aPromise.then(function taskA(value){
// task A
}).then(function taskB(vaue){
// task B
}).catch(function onRejected(error){
    console.log(error);
});
```

如果把在`then`中注册的每个回调函数称为task的话，可以通过Promise方法链方式来编写能以taskA->taskB这种流程处理的逻辑了。 

### promise chain
下面看一个稍长的例子。
```
function taskA() {
    console.log("Task A");
}

function taskB() {
    console.log("Task B");
}

function onRejected(error) {
    console.log("Catch Error: A or B", error);
}

function finalTask() {
    console.log("Final Task");
}

var promise = Promise.resolve();
promise
    .then(taskA)
    .then(taskB)
    .catch(onRejected)
    .then(finalTask);
```
![限界上下文图例](/images/promise_chain.png)<br/>
在promise chain中，由于在 onRejected 和 Final Task 后面没有 catch 处理了，因此在这两个Task中如果出现异常的话将不会被捕获，这点需要注意一下。

### taskA产生异常的例子
```
function taskA() {
    console.log("Task A");
    throw new Error("throw Error @ Task A")
}
function taskB() {
    console.log("Task B");// 不会被调用
}
function onRejected(error) {
    console.log(error);// => "throw Error @ Task A"
}
function finalTask() {
    console.log("Final Task");
}

var promise = Promise.resolve();
promise
    .then(taskA)
    .then(taskB)
    .catch(onRejected)
    .then(finalTask);
    
Task A
Error: throw Error @ Task A
Final Task
```
![限界上下文图例](/images/promise_error.png)<br/>

### promise chain如何传递参数

如果想taskA给taskB传递一个参数，则在taskA中return对应的返回值，会在taskB 执行时传给它。
```
function doubleUp(value) {
    return value * 2;
}
function increment(value) {
    return value + 1;
}
function output(value) {
    console.log(value);// => (1 + 1) * 2
}

var promise = Promise.resolve(1);
promise
    .then(increment)
    .then(doubleUp)
    .then(output)
    .catch(function(error){
        // promise chain中出现异常的时候会被调用
        console.error(error);
    });
```
![promise传值](/images/promise_value.png)<br/>
每个方法中 return 的值不仅只局限于字符串或者数值类型，也可以是对象或者promise对象等复杂类型。

return的值会由 Promise.resolve(return的返回值); 进行相应的包装处理，因此不管回调函数中会返回一个什么样的值，最终 then 的结果都是返回一个新创建的promise对象。   


## Promise#catch
`Promise#catch`只是`promise.then(undefined, onRejected);`方法的一个别名而已。也就是说这个方法用来注册当promise对象状态变为Rejected时的回调函数。   
IE8下catch函数可能会遇到问题。这时候可以用then代替catch函数。
```
var promise = Promise.reject(new Error("message"));
promise.then(undefined, function (error) {
    console.error(error);
});
```

## 每次调用then都会返回一个新创建的promise对象
从代码上乍一看， `aPromise.then(...).catch(...)` 像是针对最初的 `aPromise` 对象进行了一连串的方法链调用。

然而实际上不管是 `then` 还是 `catch` 方法调用，都返回了一个新的promise对象。   
```
var aPromise = new Promise(function (resolve) {
    resolve(100);
});
var thenPromise = aPromise.then(function (value) {
    console.log(value);
});
var catchPromise = thenPromise.catch(function (error) {
    console.error(error);
});
console.log(aPromise !== thenPromise); // => true
console.log(thenPromise !== catchPromise);// => true
```

![promise每次then之后都是新的对象](/images/promise_new.png)<br/>  

```
// 1: 对同一个promise对象同时调用 `then` 方法
var aPromise = new Promise(function (resolve) {
    resolve(100);
});
aPromise.then(function (value) {
    return value * 2;
});
aPromise.then(function (value) {
    return value * 2;
});
aPromise.then(function (value) {
    console.log("1: " + value); // => 100
})

// vs

// 2: 对 `then` 进行 promise chain 方式进行调用
var bPromise = new Promise(function (resolve) {
    resolve(100);
});
bPromise.then(function (value) {
    return value * 2;
}).then(function (value) {
    return value * 2;
}).then(function (value) {
    console.log("2: " + value); // => 100 * 2 * 2
});
```

第1种写法中并没有使用`promise`的方法链方式，这在`Promise`中是应该极力避免的写法。这种写法中的 then 调用几乎是在同时开始执行的，而且传给每个 then 方法的 value 值都是 100 。

第2中写法则采用了方法链的方式将多个 then 方法调用串连在了一起，各函数也会严格按照 `resolve → then → then → then` 的顺序执行，并且传给每个 then 方法的 value 的值都是前一个promise对象通过 return 返回的值。 


## promise 错误写法
### then的错误使用方法
```
function badAsyncCall() {
    var promise = Promise.resolve();
    promise.then(function() {
        // 任意处理
        return newVar;
    });
    return promise;
}
```
上述的问题，首先`promise.then`中产生的异常不能被外界捕获，也不能得到then的返回值。  
上述问题正确的写法：
```
function anAsyncCall() {
    var promise = Promise.resolve();
    return promise.then(function() {
        // 任意处理
        return newVar;
    });
}
```




[promise-anti-patterns](http://taoofcode.net/promise-anti-patterns/)

## 参考
[promise教程](http://liubin.org/promises-book/#how-to-write-promise)





